name: atma_kitchen
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.1.0  
  flutter_riverpod: ^2.4.10
  http: ^1.1.0
  intl: ^0.19.0
  carousel_slider: ^4.0.0
  google_fonts: ^6.2.0
  flutter_svg: ^0.22.0
  photo_view: ^0.14.0 
  video_player: ^2.2.10
  pdf: ^3.3.0
  path_provider: ^2.0.2
  open_file: ^3.0.3
  flutter_pdfview: ^1.0.5
  share: ^2.0.4
  flutter_local_notifications: ^5.0.0+4
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/UI P3L.jpg
    - images/Profile.jpg
    - images/produk/1715532022.jpg
    - images/produk/1716318134.jpg
    - images/produk/1716318285.jpg
    - images/produk/1716318311.jpg
    - images/produk/1716318812.jpg
    - images/produk/1716318904.jpg
    - images/produk/1716318985.jpg
    - images/produk/1716319043.jpg
    - images/produk/1716319086.jpg
    - images/produk/1716319165.jpg
    - images/produk/1716319235.jpg
    - images/produk/1716319353.jpg
    - images/produk/1716319408.jpg
    - images/produk/1716319493.jpg
    - images/produk/1716319553.jpg
    - images/produk/milkbun.jpg
    - images/produk/kopiluwak.jpeg
    - images/About_us.jpg
    - images/Birthday.jpg
    - images/Titipan.jpg

  

  
